## Server Config
spring:
  application:
    name: scmciwh

server:
  port: 9090
  servlet:
    context-path: /

---
# Data Source
spring:
  datasource:
    url: "jdbc:mysql://192.1.136.117:3306/scmciwh300?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
    username: root
    password: 123456

---
# Database Pool
spring:
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true

---
# Hibernate
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        use-new-id-generator-mappings: true
        ddl-auto: update
        jdbc.batch_size: 20
        order_inserts: true
        naming:
          implicit-strategy: default
    show-sql: false
    open-in-view: false

---
spring:
  redis:
    host: 47.96.73.9
    port: 6479  #可不配，因为底层默认值为6379